# Generated by Django 4.2.2 on 2024-11-16 20:18

import core.models
from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_customuser_card_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=11, region='IR', unique=True, ),
        ),
    ]
