# Generated by Django 4.2.2 on 2024-11-19 11:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator(regex='^(\\+|09|9)[0-9]{18,}$')]),
        ),
    ]
